"""Analysis of preprocessed Auftrag data.

This script reads the ``preprocessed_auftrag.csv`` file generated by
``src/preprocessing_duckdb.py`` and computes a set of descriptive metrics
required by the task description.

The metrics are:

1. **Aufträge per patient** – number of distinct orders (``AUFTRAGX``) for each
   patient (``PATISTAMMX``). For this distribution we output the mean, min,
   max and standard deviation.
2. **Timestamps per Auftrag** – number of measurement rows (i.e. timestamps) for
   each order. Again the four statistical aggregates are reported.
3. **Analyt per Auftrag** – number of distinct analytical measurements (``ANALYTX``)
   associated with each order, with the same statistical aggregates.

The script uses :pypi:`pandas` for data handling because it provides a concise
API for grouping and aggregation. The results are printed to ``stdout`` in a
human‑readable format.

Running the script directly (``python -m src.analyze_data``) will execute the
``main`` function.
"""

import pandas as pd
from pathlib import Path


def _load_data(csv_path: Path) -> pd.DataFrame:
    """Load the preprocessed CSV into a DataFrame.

    Parameters
    ----------
    csv_path: Path
        Path to ``preprocessed_auftrag.csv``.

    Returns
    -------
    pd.DataFrame
        DataFrame with appropriate dtypes. ``messtimestamp`` is parsed as a
        datetime object for potential future extensions.
    """
    # ``read_csv`` automatically infers column types; we explicitly parse the
    # timestamp column to ensure correct datetime handling.
    return pd.read_csv(csv_path, parse_dates=["messtimestamp"])


def _aggregate_metric(series: pd.Series) -> pd.Series:
    """Return mean, min, max and standard deviation for a numeric series.

    The result is a Series with index ``['mean', 'min', 'max', 'std']``.
    """
    return series.agg(["mean", "min", "max", "std"])


def compute_metrics(df: pd.DataFrame) -> dict:
    """Compute the required metrics from the preprocessed DataFrame.

    Returns a dictionary with three keys – ``orders_per_patient``,
    ``timestamps_per_order`` and ``analyt_per_order`` – each mapping to a Series
    containing the statistical aggregates.
    """
    # 1. Aufträge per patient (distinct orders per patient)
    orders_per_patient = (
        df.groupby("patientid")
        .agg({"auftragsid": pd.Series.nunique})
        .rename(columns={"auftragsid": "order_count"})["order_count"]
    )

    # 2. Timestamps per Auftrag (rows per order)
    timestamps_per_order = df.groupby("auftragsid").size()

    # 3. Analyt per Auftrag (distinct analyt per order)
    analyt_per_order = (
        df.groupby("auftragsid")
        .agg({"analyt": pd.Series.nunique})
        .rename(columns={"analyt": "analyt_count"})["analyt_count"]
    )

    return {
        "orders_per_patient": _aggregate_metric(orders_per_patient),
        "timestamps_per_order": _aggregate_metric(timestamps_per_order),
        "analyt_per_order": _aggregate_metric(analyt_per_order),
    }


def main() -> None:
    """Entry point for the analysis script.

    The CSV path is relative to the repository root as used in the original
    preprocessing script.
    """
    csv_path = Path("./data/preprocessed_auftrag.csv")
    if not csv_path.is_file():
        raise FileNotFoundError(f"Expected preprocessed data at {csv_path!s}")

    df = _load_data(csv_path)
    metrics = compute_metrics(df)

    # Pretty‑print the results
    for name, series in metrics.items():
        print(f"\nMetric: {name.replace('_', ' ').title()}")
        print(series.to_string())


if __name__ == "__main__":
    main()